name: Integration links

on:
    schedule:
      - cron: '0 0 * * *'
    workflow_dispatch:

permissions:
    contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - name: Run the script
      run: deno run --allow-read --allow-write --allow-net index.ts

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "[${{ github.event.repository.updated_at}}] update links"