name: Integration links

on:
    schedule:
      - cron: '0 0 * * *'
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - name: Run the script
      run: deno run --allow-read --allow-write --allow-net index.ts

    - name: Commit updated links
      uses: devops-infra/action-commit-push@v0.9.2
      with:
        github_token: "${{ secrets.GITHUB_TOKEN }}"
        add_timestamp: true
        commit_prefix: "[AUTO]"
        commit_message: "${{ github.event.repository.updated_at}}: update links"
        force: false
        target_branch: update/version